USE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
USE WAREHOUSE DASH_WH_SI;
USE DATABASE DASH_DB_SI;
USE SCHEMA RETAIL;

CREATE OR REPLACE CORTEX SEARCH SERVICE SUPPORT_CASES
    ON TRANSCRIPT
    ATTRIBUTES TITLE, PRODUCT
    WAREHOUSE = DASH_WH_SI
    TARGET_LAG = '1 hour'
AS (
    SELECT *
    FROM DASH_DB_SI.RETAIL.SUPPORT_CASES
);

-- Grant access to SNOWFLAKE_INTELLIGENCE_ADMIN
USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE DASH_DB_SI TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT USAGE ON SCHEMA DASH_DB_SI.RETAIL TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT USAGE ON CORTEX SEARCH SERVICE DASH_DB_SI.RETAIL.SUPPORT_CASES TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT SELECT ON TABLE DASH_DB_SI.RETAIL.SUPPORT_CASES TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
GRANT USAGE ON WAREHOUSE DASH_WH_SI TO ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
